markdown: kramdown

exclude:
- ".gitignore"
- README.md
- CONTRIBUTING.md
- LICENSE.pdf

# Site metadata
name: "Modalités d'ouverture des codes sources"
description: "Achieving Efficiency, Transparency, and Innovation through Reusable and Open Source Software"
# baseurl: https:// A DETERMINER

# GitHub information
org_name: DISIC
repo_name: politique-de-contribution-open-source
branch: gh-pages

# Navigation
navigation:
- text: Introduction
  url: /
- text: 1 - Modalités d'ouverture
  url: /Ouverture
- text: 2 - Meilleurs pratiques
  url: /Pratique
- text: 3 - Instanciation 
  url: /Instanciation
- text: 4 - Gouvernance
url: /Gouvernance
